// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: addressbook.proto

package com.apoorvbansalgloballogicnoida.protos;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tutorial.AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .tutorial.Person person = 1;</code>
   */
  java.util.List<com.apoorvbansalgloballogicnoida.protos.Person> 
      getPersonList();
  /**
   * <code>repeated .tutorial.Person person = 1;</code>
   */
  com.apoorvbansalgloballogicnoida.protos.Person getPerson(int index);
  /**
   * <code>repeated .tutorial.Person person = 1;</code>
   */
  int getPersonCount();
  /**
   * <code>repeated .tutorial.Person person = 1;</code>
   */
  java.util.List<? extends com.apoorvbansalgloballogicnoida.protos.PersonOrBuilder> 
      getPersonOrBuilderList();
  /**
   * <code>repeated .tutorial.Person person = 1;</code>
   */
  com.apoorvbansalgloballogicnoida.protos.PersonOrBuilder getPersonOrBuilder(
      int index);
}
